name: Link Checker

on:
    pull_request:
        paths:
            - "README.md"
    schedule:
        # Runs every 2nd day at midnight UTC
        - cron: "0 0 */2 * *"
    # Allows manual triggering
    workflow_dispatch:

jobs:
    check_links_pr:
        name: Check Links (PR)
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Check links in README.md
              uses: lycheeverse/lychee-action@v2
              with:
                  args: >
                      --verbose
                      --no-progress
                      --max-concurrency 64
                      --retry-wait-time 5
                      --max-retries 3
                      --exclude-mail
                      README.md
                  # Exclude mailto links, retry 3 times with 5s wait

    check_and_archive_links:
        name: Check & Archive Dead Links
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        steps:
            - name: Create GitHub App token
              id: app-token
              uses: actions/create-github-app-token@v1
              with:
                  app-id: ${{ secrets.BOT_ID }}
                  private-key: ${{ secrets.BOT_SK }}

            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  token: ${{ steps.app-token.outputs.token }}
                  fetch-depth: 0

            - name: Check for existing PRs
              id: check-prs
              run: |
                  PR_COUNT=$(gh pr list --base main --head chore/archive-dead-links --json number --jq length)
                  echo "has_existing_pr=$([[ $PR_COUNT -gt 0 ]] && echo "true" || echo "false")" >> $GITHUB_OUTPUT
              env:
                  GH_TOKEN: ${{ steps.app-token.outputs.token }}

            - name: Check links and save report
              id: lychee
              if: steps.check-prs.outputs.has_existing_pr == 'false'
              uses: lycheeverse/lychee-action@v2
              with:
                  args: >
                      --verbose
                      --no-progress
                      --max-concurrency 64
                      --retry-wait-time 5
                      --max-retries 3
                      --exclude-mail
                      --format json
                      --output report.json
                      README.md
              continue-on-error: true # Continue even if links fail

            - name: Set up Python
              if: steps.check-prs.outputs.has_existing_pr == 'false' && steps.lychee.outputs.exit_code != '0'
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"
                  cache: pip

            - name: Handle dead links
              id: handle_links
              if: steps.check-prs.outputs.has_existing_pr == 'false' && steps.lychee.outputs.exit_code != '0'
              run: |
                  python .github/scripts/handle-dead-links.py report.json README.md ARCHIVED.md

                  # Check if any changes were made
                  if git diff --name-only | grep -q "ARCHIVED.md\|README.md"; then
                    echo "changes_made=true" >> $GITHUB_OUTPUT
                  else
                    echo "changes_made=false" >> $GITHUB_OUTPUT
                  fi

            - name: Create branch and commit changes
              if: steps.check-prs.outputs.has_existing_pr == 'false' && steps.handle_links.outputs.changes_made == 'true'
              run: |
                  # Configure Git
                  git config user.name "github-actions[bot]"
                  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

                  # Create branch
                  git checkout -b chore/archive-dead-links

                  # Add changes
                  git add README.md ARCHIVED.md

                  # Commit changes
                  git commit -m "chore: Archive dead links found by link checker"

                  # Push changes
                  git push origin chore/archive-dead-links

            - name: Create Pull Request
              if: steps.check-prs.outputs.has_existing_pr == 'false' && steps.handle_links.outputs.changes_made == 'true'
              run: |
                  # Create pull request
                  gh pr create \
                    --title "chore: Archive dead links from README" \
                    --body "The scheduled link checker found links in \`README.md\` that failed verification after multiple retries.

                  These entries have been moved to \`ARCHIVED.md\`. Please review:
                  - Verify if the projects/resources are truly defunct.
                  - If a link just needs updating, please correct it in \`README.md\` and remove the entry from \`ARCHIVED.md\`.
                  - If the resource is gone, this PR can be merged as is.

                  *This PR was automatically generated.*" \
                    --label "maintenance,automated pr" \
                    --base main \
                    --head chore/archive-dead-links
              env:
                  GH_TOKEN: ${{ steps.app-token.outputs.token }}
