name: Link Checker

on:
    pull_request:
        paths:
            - "README.md"
    schedule:
        # Runs every 2nd day at midnight UTC
        - cron: "0 0 */2 * *"
    # Allows manual triggering
    workflow_dispatch:

jobs:
    check_links_pr:
        name: Check Links (PR)
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Check links in README.md
              uses: lycheeverse/lychee-action@v2
              with:
                  args: --config .github/workflows/lychee.toml --verbose --no-progress README.md

