name: Post Merge actions
on:
    push:
        branches:
            - main

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    post-merge-actions:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Run linters
              run: npx awesome-lint
